project:
  type: website

website:
  title: "Visualizing Incarceration"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - data.qmd
      - map.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

